(() => {
"use strict";
const API_URL = "https://studmart.onrender.com/api";
const CATEGORIES=[
 {name:"Books & notes",emoji:"📚",hint:"Textbooks and study notes"},
 {name:"Tech & gadgets",emoji:"🎧",hint:"Phones, laptops and accessories"},
 {name:"Fashion",emoji:"👟",hint:"Style, shoes and accessories"},
 {name:"Hostel & room",emoji:"🪴",hint:"Room essentials and decor"},
 {name:"Food & groceries",emoji:"🍜",hint:"Snacks and everyday essentials"},
 {name:"Services",emoji:"🛠️",hint:"Skills and student services"},
 {name:"Sports & fitness",emoji:"🏀",hint:"Sports gear and fitness"},
 {name:"Other",emoji:"✨",hint:"More campus finds"}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,token:localStorage.getItem("studmartToken")||"",products:[],saved:new Set(),filter:"All",search:"",sort:"newest",activeProduct:null,conversations:[],activeConversation:null,poll:null};
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function money(n){return "₦"+Number(n||0).toLocaleString("en-NG",{maximumFractionDigits:2});}
function initials(name="Student"){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase()||"ST";}
function category(name){return CATEGORIES.find(c=>c.name===name)||CATEGORIES[CATEGORIES.length-1];}
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2800);}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.token)headers.Authorization="Bearer "+state.token;
 let res;try{res=await fetch(API_BASE+path,{...options,headers});}catch(e){throw new Error("Cannot reach the backend. Check the API URL and make sure your server is running.");}
 const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||data.message||"Request failed.");return data;}
function setMessage(el,msg,type=""){if(!el)return;el.textContent=msg;el.className="form-message "+type;}
function authMode(mode){$("#loginPane").classList.toggle("hidden",mode!=="login");$("#registerPane").classList.toggle("hidden",mode!=="register");$$("[data-auth-mode]").forEach(b=>b.classList.toggle("active",b.dataset.authMode===mode));}
function go(view){const target=$("#view-"+view);if(!target){view="home";}
 $$(".view").forEach(v=>v.classList.toggle("active",v.id==="view-"+view));$$("[data-view]").forEach(b=>b.classList.toggle("active",b.classList.contains("nav-link")&&b.dataset.view===view));
 if(view==="profile")renderProfile();if(view==="saved")renderSaved();if(view==="messages")loadConversations();if(view==="market")renderMarket();window.scrollTo({top:0,behavior:"smooth"});history.replaceState(null,"","#"+view);}
function renderCategories(){const card=c=>`<button class="category-card" data-category="${esc(c.name)}"><span class="category-emoji">${c.emoji}</span><strong>${esc(c.name)}</strong><small>${esc(c.hint)}</small></button>`;
 $("#homeCategories").innerHTML=CATEGORIES.slice(0,6).map(card).join("");$("#allCategories").innerHTML=CATEGORIES.map(card).join("");$("#listingCategory").innerHTML=CATEGORIES.map(c=>`<option>${esc(c.name)}</option>`).join("");
 $("#marketChips").innerHTML=["All",...CATEGORIES.map(c=>c.name)].map(c=>`<button class="chip ${state.filter===c?"active":""}" data-filter="${esc(c)}">${esc(c)}</button>`).join("");}
function productEmoji(p){const c=category(p.category);return c.emoji||"✨";}
function productImage(p){const url=p.imageUrl||p.image||p.image_url||"";if(url&&/^https?:\/\//i.test(url))return `<img src="${esc(url)}" alt="${esc(p.title||"Product")}" loading="lazy" onerror="this.remove()">`;return `<span class="emoji">${productEmoji(p)}</span>`;}
function sellerName(p){return p.sellerName||p.seller?.name||p.ownerName||p.user?.name||"STUDMART student";}
function productId(p){return String(p.id??p._id??p.listingId??"");}
function card(p,i=0){const id=productId(p),isSaved=state.saved.has(id);return `<article class="product-card" data-product="${esc(id)}" style="animation-delay:${Math.min(i,8)*.045}s"><div class="product-art">${productImage(p)}<span class="product-status">${esc(p.condition||"Student listing")}</span><button class="save-button ${isSaved?"saved":""}" data-save="${esc(id)}" aria-label="${isSaved?"Remove saved item":"Save item"}">${isSaved?"♥":"♡"}</button></div><div class="product-info"><span class="product-category">${esc(p.category||"Other")}</span><h3 title="${esc(p.title)}">${esc(p.title||"Untitled listing")}</h3><div class="product-price">${money(p.price)}</div><div class="product-details"><span>⌖ ${esc(p.location||p.campus||"Campus")}</span><span>·</span><span>${esc(p.condition||"Listed by student")}</span></div><div class="seller-line"><span class="seller-initial">${esc(initials(sellerName(p)))}</span><span>${esc(sellerName(p))}</span><span class="seller-school">${esc(p.campus||"Student")}</span></div></div></article>`;}
function empty(title,desc,button="Explore marketplace",view="market"){return `<div class="empty-state"><div>♡</div><h2>${esc(title)}</h2><p>${esc(desc)}</p><button class="button" data-view="${view}">${esc(button)} ↗</button></div>`;}
async function loadProducts(){try{const data=await api("/listings");state.products=Array.isArray(data)?data:(data.listings||data.items||data.data||[]);renderHomeProducts();renderMarket();if(state.user)await loadSaved();}catch(e){state.products=[];renderHomeProducts();renderMarket();toast(e.message);}}
function renderHomeProducts(){const items=state.products.slice().sort((a,b)=>new Date(b.createdAt||b.created_at||0)-new Date(a.createdAt||a.created_at||0)).slice(0,6);$("#homeProducts").innerHTML=items.length?items.map(card).join(""):empty("No listings yet","Be the first student to post an item.","Sell the first item","sell");}
function filteredProducts(){let arr=state.products.filter(p=>(state.filter==="All"||p.category===state.filter)&&(!state.search||(p.title+" "+p.description+" "+p.category+" "+(p.location||"")).toLowerCase().includes(state.search.toLowerCase())));
 if(state.sort==="price-low")arr.sort((a,b)=>Number(a.price)-Number(b.price));else if(state.sort==="price-high")arr.sort((a,b)=>Number(b.price)-Number(a.price));else arr.sort((a,b)=>new Date(b.createdAt||b.created_at||0)-new Date(a.createdAt||a.created_at||0));return arr;}
function renderMarket(){if(!$("#marketProducts"))return;const arr=filteredProducts();$("#resultCount").textContent=`${arr.length} item${arr.length===1?"":"s"} found`;$("#marketProducts").innerHTML=arr.length?arr.map(card).join(""):empty("No items found","Try a different search or category, or check back soon.");$("#marketChips").innerHTML=["All",...CATEGORIES.map(c=>c.name)].map(c=>`<button class="chip ${state.filter===c?"active":""}" data-filter="${esc(c)}">${esc(c)}</button>`).join("");}
function renderSaved(){const items=state.products.filter(p=>state.saved.has(productId(p)));$("#savedProducts").innerHTML=items.length?items.map(card).join(""):empty("Your saved list is waiting","Tap the heart on a listing to keep it here.",state.user?"Explore marketplace":"Log in to save items",state.user?"market":"auth");}
async function loadSaved(){if(!state.token){state.saved=new Set(JSON.parse(localStorage.getItem("studmartSaved")||"[]").map(String));updateSavedDot();return;}try{const d=await api("/saved");const items=Array.isArray(d)?d:(d.saved||d.items||[]);state.saved=new Set(items.map(x=>String(x.listingId??x.listing_id??x.id??x)));localStorage.setItem("studmartSaved",JSON.stringify([...state.saved]));}catch(e){state.saved=new Set(JSON.parse(localStorage.getItem("studmartSaved")||"[]").map(String));}updateSavedDot();}
function updateSavedDot(){$("#savedDot").classList.toggle("on",state.saved.size>0);}
async function toggleSave(id){if(!id)return;if(!state.token){const exists=state.saved.has(id);exists?state.saved.delete(id):state.saved.add(id);localStorage.setItem("studmartSaved",JSON.stringify([...state.saved]));updateSavedDot();renderHomeProducts();renderMarket();renderSaved();toast(exists?"Removed from saved items":"Saved on this device. Log in to sync across devices.");return;}
 try{if(state.saved.has(id)){await api("/saved/"+encodeURIComponent(id),{method:"DELETE"});state.saved.delete(id);toast("Removed from saved items");}else{await api("/saved",{method:"POST",body:JSON.stringify({listingId:id})});state.saved.add(id);toast("Added to saved items");}localStorage.setItem("studmartSaved",JSON.stringify([...state.saved]));updateSavedDot();renderHomeProducts();renderMarket();renderSaved();}catch(e){toast(e.message);}}
function openProduct(id){const p=state.products.find(x=>productId(x)===String(id));if(!p)return;state.activeProduct=p;const url=p.imageUrl||p.image||p.image_url||"";$("#modalContent").innerHTML=`<div class="modal-product-image">${url&&/^https?:\/\//i.test(url)?`<img src="${esc(url)}" alt="${esc(p.title)}" onerror="this.remove()">`:productEmoji(p)}</div><span class="modal-category">${esc(p.category||"Other")} · ${esc(p.condition||"Student listing")}</span><h2 class="modal-title" id="modalTitle">${esc(p.title)}</h2><div class="modal-price">${money(p.price)}</div><p class="modal-description">${esc(p.description||"No description provided.")}</p><div class="modal-meta">⌖ ${esc(p.location||p.campus||"Campus")} · Listed by ${esc(sellerName(p))}</div><div class="modal-actions"><button class="button" id="messageSeller">Message seller ↗</button><button class="button button-ghost" id="modalSave">${state.saved.has(productId(p))?"♥ Saved":"♡ Save item"}</button></div><p class="muted">Safety tip: meet in a public place and agree on payment directly. STUDMART does not hold payments.</p>`;
 $("#productModal").classList.add("open");$("#messageSeller").addEventListener("click",()=>startConversation(p));$("#modalSave").addEventListener("click",()=>toggleSave(productId(p)));}
function closeModal(){$("#productModal").classList.remove("open");state.activeProduct=null;}
async function authRestore(){if(!state.token)return;try{const d=await api("/me");state.user=d.user||d;updateAuthUI();}catch(e){state.token="";localStorage.removeItem("studmartToken");state.user=null;updateAuthUI();}}
function updateAuthUI(){$("#authTop").textContent=state.user?initials(state.user.name||state.user.fullName||state.user.email):"GO";$("#authTop").title=state.user?"Account":"Log in";if(state.user)loadSaved();}
async function handleLogin(event){event.preventDefault();const form=event.currentTarget;const msg=$("#loginMessage");setMessage(msg,"Signing you in…");const fd=new FormData(form);try{const d=await api("/auth/login",{method:"POST",body:JSON.stringify({email:fd.get("email"),password:fd.get("password")})});state.token=d.token||d.accessToken||"";if(!state.token)throw new Error("Login response did not include a token.");localStorage.setItem("studmartToken",state.token);state.user=d.user||null;if(!state.user){const me=await api("/me");state.user=me.user||me;}form.reset();setMessage(msg,"");updateAuthUI();await loadSaved();toast("Welcome back, "+(state.user.name||"student")+"!");go("profile");}catch(e){setMessage(msg,e.message,"error");}}
async function handleRegister(event){event.preventDefault();const form=event.currentTarget;const msg=$("#registerMessage");setMessage(msg,"Creating your account…");const fd=new FormData(form);const body={name:fd.get("name"),email:fd.get("email"),password:fd.get("password"),department:fd.get("department"),level:fd.get("level"),campus:fd.get("campus")};try{const d=await api("/auth/register",{method:"POST",body:JSON.stringify(body)});if(d.token){state.token=d.token;localStorage.setItem("studmartToken",state.token);state.user=d.user||null;if(!state.user){const me=await api("/me");state.user=me.user||me;}updateAuthUI();toast("Welcome to STUDMART!");go("profile");}else{setMessage(msg,"Account created. Please log in.","success");authMode("login");$("#loginForm [name=email]").value=body.email;}form.reset();}catch(e){setMessage(msg,e.message,"error");}}
async function renderProfile(){const host=$("#profileContent");if(!state.user){host.innerHTML=empty("Sign in to see your profile","Access your listings and update your student details.","Log in or create account","auth");return;}
 let user=state.user;host.innerHTML=`<div class="panel"><div class="profile-banner"></div><div class="profile-info-row"><div class="profile-avatar">${esc(initials(user.name||user.email))}</div><div class="profile-details"><h2>${esc(user.name||"Student")}</h2><p>${esc(user.email||"")}</p><p>${esc([user.department,user.level,user.campus].filter(Boolean).join(" · ")||"Add your student details below")}</p></div><div class="profile-buttons"><button class="button button-ghost" id="logoutBtn">Log out</button></div></div><div class="profile-stats"><div><strong>${state.products.filter(p=>String(p.sellerId||p.userId||p.ownerId||"")===String(user.id||user._id||"")).length}</strong><small>My listings (approx.)</small></div><div><strong>${state.saved.size}</strong><small>Saved items</small></div><div><strong>STUDENT</strong><small>Community member</small></div></div></div><form class="panel profile-form" id="profileForm" style="margin-top:18px"><h3>Profile details</h3><p class="muted">Keep your information up to date.</p><label>Full name<input name="name" required maxlength="80" value="${esc(user.name||"")}"></label><div class="form-row"><label>Department<input name="department" maxlength="100" value="${esc(user.department||"")}"></label><label>Level<input name="level" maxlength="30" value="${esc(user.level||"")}"></label></div><label>Campus / school<input name="campus" maxlength="120" value="${esc(user.campus||"")}"></label><button class="button" type="submit">Save profile changes ↗</button><p class="form-message" id="profileMessage"></p></form>`;
 $("#logoutBtn").addEventListener("click",logout);$("#profileForm").addEventListener("submit",saveProfile);}
async function saveProfile(e){e.preventDefault();const form=e.currentTarget,fd=new FormData(form),msg=$("#profileMessage");const body=Object.fromEntries(["name","department","level","campus"].map(k=>[k,fd.get(k)]));setMessage(msg,"Saving…");try{const d=await api("/profile",{method:"PATCH",body:JSON.stringify(body)});state.user=d.user||d.profile||d;setMessage(msg,"Profile updated successfully.","success");updateAuthUI();renderProfile();toast("Profile updated");}catch(err){setMessage(msg,err.message,"error");}}
async function logout(){try{if(state.token)await api("/auth/logout",{method:"POST"});}catch(e){}state.token="";state.user=null;state.conversations=[];state.activeConversation=null;localStorage.removeItem("studmartToken");updateAuthUI();toast("You have been logged out");go("home");}
async function submitListing(e){e.preventDefault();if(!state.token){toast("Please log in before publishing a listing.");go("auth");authMode("login");return;}const form=e.currentTarget,fd=new FormData(form),msg=$("#listingMessage");const body={title:fd.get("title"),category:fd.get("category"),price:Number(fd.get("price")),description:fd.get("description"),location:fd.get("location"),condition:fd.get("condition"),imageUrl:fd.get("imageUrl")};setMessage(msg,"Publishing your listing…");try{const d=await api("/listings",{method:"POST",body:JSON.stringify(body)});const item=d.listing||d.item||d;state.products.unshift(item);form.reset();setMessage(msg,"Your listing is live!","success");renderHomeProducts();renderMarket();toast("Listing published");go("market");}catch(err){setMessage(msg,err.message,"error");}}
async function loadConversations(){if(!state.token){$("#conversationList").innerHTML='<div class="empty-mini">Log in to see your conversations.</div>';return;}try{const d=await api("/conversations");state.conversations=Array.isArray(d)?d:(d.conversations||d.items||[]);renderConversations();}catch(e){$("#conversationList").innerHTML=`<div class="empty-mini">${esc(e.message)}</div>`;}}
function conversationId(c){return String(c.id??c._id??c.conversationId??"");}
function otherPerson(c){return c.otherUser||c.seller||c.recipient||c.participant||{};}
function renderConversations(){$("#conversationList").innerHTML=state.conversations.length?state.conversations.map(c=>{const person=otherPerson(c),id=conversationId(c);return `<button class="conversation-item ${state.activeConversation===id?"active":""}" data-conversation="${esc(id)}"><span class="conversation-avatar">${esc(initials(person.name||c.otherName||"Student"))}</span><span><strong>${esc(person.name||c.otherName||"Student")}</strong><small>${esc(c.lastMessage||c.productTitle||"Open conversation")}</small></span></button>`;}).join():'<div class="empty-mini">No conversations yet. Open a listing and message the seller.</div>';}
async function startConversation(p){closeModal();if(!state.token){toast("Log in to message sellers.");go("auth");authMode("login");return;}try{const d=await api("/conversations",{method:"POST",body:JSON.stringify({listingId:productId(p),recipientId:p.sellerId||p.userId||p.ownerId})});const c=d.conversation||d;const id=conversationId(c);if(!id)throw new Error("Conversation started but no conversation ID was returned.");await loadConversations();state.activeConversation=id;go("messages");await openConversation(id);}catch(e){toast(e.message);}}
async function openConversation(id){state.activeConversation=String(id);renderConversations();const c=state.conversations.find(x=>conversationId(x)===String(id))||{};const person=otherPerson(c);$(".chat-empty").classList.add("hidden");$("#chatActive").classList.remove("hidden");$("#chatHeader").innerHTML=`<span class="conversation-avatar">${esc(initials(person.name||c.otherName||"Student"))}</span><span>${esc(person.name||c.otherName||"Student")}<small style="display:block;color:var(--green);font-size:9px;font-weight:500">STUDMART conversation</small></span>`;
 await loadMessages(id);}
async function loadMessages(id){try{const d=await api("/conversations/"+encodeURIComponent(id)+"/messages");const messages=Array.isArray(d)?d:(d.messages||d.items||[]);$("#chatMessages").innerHTML=messages.map(m=>{const mine=String(m.senderId||m.sender_id||m.userId||"")===String(state.user?.id||state.user?._id||"");return `<div class="chat-bubble ${mine?"mine":""}">${esc(m.text||m.message||m.content||"")}<time>${esc(m.createdAt?new Date(m.createdAt).toLocaleString(): "")}</time></div>`;}).join()||'<p class="muted">Say hello to start the conversation.</p>';$("#chatMessages").scrollTop=$("#chatMessages").scrollHeight;}catch(e){$("#chatMessages").innerHTML=`<p class="muted">${esc(e.message)}</p>`;}}
async function sendMessage(e){e.preventDefault();const form=e.currentTarget,fd=new FormData(form),input=form.elements.message,text=String(fd.get("message")||"").trim();if(!text||!state.activeConversation)return;input.value="";try{await api("/conversations/"+encodeURIComponent(state.activeConversation)+"/messages",{method:"POST",body:JSON.stringify({message:text,text})});await loadMessages(state.activeConversation);await loadConversations();}catch(e){input.value=text;toast(e.message);}}
function bindEvents(){document.addEventListener("click",e=>{const nav=e.target.closest("[data-view]");if(nav){e.preventDefault();go(nav.dataset.view);return;}const cat=e.target.closest("[data-category]");if(cat){state.filter=cat.dataset.category;go("market");renderMarket();return;}const chip=e.target.closest("[data-filter]");if(chip){state.filter=chip.dataset.filter;renderMarket();return;}const save=e.target.closest("[data-save]");if(save){e.stopPropagation();toggleSave(save.dataset.save);return;}const conv=e.target.closest("[data-conversation]");if(conv){openConversation(conv.dataset.conversation);return;}const prod=e.target.closest("[data-product]");if(prod){openProduct(prod.dataset.product);return;}const mode=e.target.closest("[data-auth-mode]");if(mode){authMode(mode.dataset.authMode);return;}});
 $("#globalSearch").addEventListener("input",e=>{state.search=e.target.value;renderMarket();});$("#globalSearch").addEventListener("keydown",e=>{if(e.key==="Enter"){go("market");renderMarket();}});
 $("#sortSelect").addEventListener("change",e=>{state.sort=e.target.value;renderMarket();});$("#clearFilters").addEventListener("click",()=>{state.filter="All";state.search="";$("#globalSearch").value="";$("#sortSelect").value="newest";renderMarket();});
 $("#closeModal").addEventListener("click",closeModal);$("#productModal").addEventListener("click",e=>{if(e.target.id==="productModal")closeModal();});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal();});
 $("#loginForm").addEventListener("submit",handleLogin);$("#registerForm").addEventListener("submit",handleRegister);$("#listingForm").addEventListener("submit",submitListing);$("#messageForm").addEventListener("submit",sendMessage);
}
async function init(){renderCategories();bindEvents();updateAuthUI();await authRestore();await loadProducts();if(location.hash&&$("#view-"+location.hash.slice(1)))go(location.hash.slice(1));}
init();
})();
